version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: jungle
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wagering
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jungle -d wagering"]
      interval: 5s
      timeout: 5s
      retries: 5

  sqs:
    image: softwaremill/elasticmq-native:latest
    ports:
      - "4566:9324"            # SQS Gateway (mapping 4566 to match localstack config)
    volumes:
      - "./elasticmq.conf:/opt/elasticmq.conf"

volumes:
  pgdata:
