include classpath("application.conf")

node-address {
    protocol = http
    host = "*"
    port = 9324
    context-path = ""
}

rest-sqs {
    enabled = true
    bind-port = 9324
    bind-hostname = "0.0.0.0"
    sqs-limits = relaxed
}

queues {
    "wager-transactions-dlq.fifo" {
        defaultVisibilityTimeout = 30 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
        fifo = true
        contentBasedDeduplication = true
    }
    "wager-transactions.fifo" {
        defaultVisibilityTimeout = 30 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
        deadLettersQueue {
            name = "wager-transactions-dlq.fifo"
            maxReceiveCount = 3
        }
        fifo = true
        contentBasedDeduplication = true
    }
    "outbox-events.fifo" {
        defaultVisibilityTimeout = 30 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
        fifo = true
        contentBasedDeduplication = true
    }
}
